version: "3"
services:
  api_service:
    build: .
    environment:
      #- SERVER_PORT=8083
      - SPRING_DATA_MONGODB_HOST=mongo_db
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=axon_schema
      - AXON_AXONSERVER_SERVERS=axon-server
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo_db
      - axon-server
  mongo_db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  axon-server:
    image: axoniq/axonserver
    container_name: axon-server
    ports:
      - 8124:8124
      - 8024:8024